version: "3.8"

services:
  nuxt-app:
    image: sobol4156/nuxt:auto-deploy
    container_name: nuxt-auto-deploy
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: always
