name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.3.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: sobol4156/nuxt:auto-deploy

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP}}
          username: ${{ secrets.SERVER_USER}}
          key: ${{ secrets.SECRET_AUTO_DEPLOY }}
          port: 22
          script: |
            cd ~/auto-deploy-nuxt
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker compose down --remove-orphans
            docker network prune -f
            docker container prune -f
            docker compose pull
            docker compose up -d