name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SECRET_AUTO_DEPLOY }}

      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 45.142.36.179 >> ~/.ssh/known_hosts

      - name: Copy files to the server
        run: |
          scp -r ./.output/* root@45.142.36.179:~/auto-deploy-nuxt
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_AUTO_DEPLOY }}

      - name: Restart the server
      run: |
          ssh root@45.142.36.179 "cd ~/auto-deploy-nuxt && npm install && npm run dev"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_AUTO_DEPLOY }}
